# Generated by Django 4.1.7 on 2023-03-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
